# ====== BASE DE DATOS (PostgreSQL) ======
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always


# =========================================================
# ======================= SERVIDOR ========================
# =========================================================

server.port=${PORT:8080}


# =========================================================
# ======================= HIKARI CP =======================
# =========================================================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=300000


# =========================================================
# ======================== MAIL ===========================
# =========================================================

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:465}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:false}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_STARTTLS_REQUIRED:false}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SSL_ENABLE:true}
notificaciones.correo.habilitado=${NOTIFICACIONES_CORREO_HABILITADO:true}


# =========================================================
# ========================= JWT ===========================
# =========================================================

jwt.secret=secretsecretsecretsecretsecretsecretsecretsecret


# =========================================================
# ======================= SWAGGER =========================
# =========================================================

springdoc.swagger-ui.path=/doc/swagger-ui.html


# =========================================================
# ====================== CLOUDINARY =======================
# =========================================================

cloudinary.cloud_name=dl2h9wlm3
cloudinary.api_key=145922535687464
cloudinary.api_secret=y-ERrv3N_tpHMLvHYlNiRhnBUUs

# ======================== NOTIFICACIONES =========================
notificaciones.whatsapp.habilitado=false
notificaciones.whatsapp.api-url=https://api.callmebot.com/whatsapp.php
notificaciones.whatsapp.api-key=
notificaciones.whatsapp.prefijo-pais=57

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
