ALTER TABLE empresa ADD COLUMN IF NOT EXISTS tributo_codigo VARCHAR(10);
ALTER TABLE empresa ADD COLUMN IF NOT EXISTS tributo_nombre VARCHAR(100);
ALTER TABLE cliente ADD COLUMN IF NOT EXISTS tributo_codigo VARCHAR(10);
ALTER TABLE cliente ADD COLUMN IF NOT EXISTS tributo_nombre VARCHAR(100);
