ALTER TABLE venta ADD COLUMN IF NOT EXISTS es_domicilio BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE venta ADD COLUMN IF NOT EXISTS direccion_domicilio VARCHAR(500);
ALTER TABLE venta ADD COLUMN IF NOT EXISTS costo_domicilio DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE venta ADD COLUMN IF NOT EXISTS nombre_recibe_domicilio VARCHAR(255);
ALTER TABLE venta ADD COLUMN IF NOT EXISTS celular_recibe_domicilio VARCHAR(50);
