ALTER TABLE empresa ADD COLUMN IF NOT EXISTS municipio_nombre VARCHAR(100);
ALTER TABLE empresa ADD COLUMN IF NOT EXISTS departamento_nombre VARCHAR(100);
ALTER TABLE empresa ADD COLUMN IF NOT EXISTS pais_nombre VARCHAR(100);

ALTER TABLE sede ADD COLUMN IF NOT EXISTS municipio_nombre VARCHAR(100);
ALTER TABLE sede ADD COLUMN IF NOT EXISTS departamento_nombre VARCHAR(100);
ALTER TABLE sede ADD COLUMN IF NOT EXISTS pais_nombre VARCHAR(100);

ALTER TABLE cliente ADD COLUMN IF NOT EXISTS municipio_nombre VARCHAR(100);
ALTER TABLE cliente ADD COLUMN IF NOT EXISTS departamento_nombre VARCHAR(100);
ALTER TABLE cliente ADD COLUMN IF NOT EXISTS pais_nombre VARCHAR(100);

ALTER TABLE producto ADD COLUMN IF NOT EXISTS precio_incluye_impuestos BOOLEAN;
